package com.lulapps.vivienda360;

import android.content.Context;
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentTransaction;
import androidx.navigation.Navigation;

import android.text.Editable;
import android.text.TextWatcher;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.inputmethod.InputMethodManager;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.TextView;

import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.LatLngBounds;
import com.google.android.gms.maps.model.MarkerOptions;
import com.google.android.gms.maps.model.PolygonOptions;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;

public class SeccionBuscarFragment extends Fragment implements OnMapReadyCallback {

    AutoCompleteTextView espacio_barrio;
    Button botonAceptar;
    Button botonVenta;
    Button botonArriendo;
    TextView publicarInmueble;

    boolean ofertaTipoVenta=true;

    ArrayList<Zona> zonas_bogota;
    private static final String[] barrios_y_localidades = new String[] {
            "ANTONIO NARIÑO - LOCALIDAD", "TUNJUELITO - LOCALIDAD", "RAFAEL URIBE URIBE - LOCALIDAD", "CANDELARIA - LOCALIDAD", "BARRIOS UNIDOS - LOCALIDAD", "TEUSAQUILLO - LOCALIDAD", "PUENTE ARANDA - LOCALIDAD", "LOS MARTIRES - LOCALIDAD", "SUMAPAZ - LOCALIDAD", "USAQUEN - LOCALIDAD", "CHAPINERO - LOCALIDAD", "SANTA FE - LOCALIDAD", "SAN CRISTOBAL - LOCALIDAD", "USME - LOCALIDAD", "CIUDAD BOLIVAR - LOCALIDAD", "BOSA - LOCALIDAD", "KENNEDY - LOCALIDAD", "FONTIBON - LOCALIDAD", "ENGATIVA - LOCALIDAD", "SUBA - LOCALIDAD", "EL JARDIN (BOSA)", "SAN RAFAEL (PUENTE ARANDA)", "PUERTA DEL SOL (SUBA)", "EL REFUGIO (FONTIBON)", "ATAHUALPA (FONTIBON)", "SAN JOSE DE FONTIBON (FONTIBON)", "VERSALLES FONTIBON (FONTIBON)", "AEROPUERTO EL DORADO (FONTIBON)", "LA CABANA FONTIBON (FONTIBON)", "BRISAS ALDEA FONTIBON (FONTIBON)", "CIUDADELA EL RECREO (BOSA)", "EL SALTEADOR (USME)", "COLMENA I LOS PINARES (SAN CRISTOBAL)", "SAN ISIDRO (SAN CRISTOBAL)", "VILLA ALSACIA II (KENNEDY)", "COOPERATIVA DE SUB-OFICIALES (KENNEDY)", "TIMIZA (KENNEDY)", "CIUDAD KENNEDY ORIENTAL (KENNEDY)", "CHUNIZA (USME)", "DESARROLLO BRAZUELOS I (USME)", "LAS CRUCES (SANTA FE)", "CAMPIN OCCIDENTAL (TEUSAQUILLO)", "NICOLAS DE FEDERMAN (TEUSAQUILLO)", "ROMA (KENNEDY)", "ARRAYANES I (USME)", "SERRANIAS I (USME)", "LA ESPERANZA NORTE (FONTIBON)", "ALCAZARES (BARRIOS UNIDOS)", "CAMPO EUCARISTICO (TEUSAQUILLO)", "CAPELLANIA (FONTIBON)", "ESPINO (CIUDAD BOLIVAR)", "PATIO BONITO III (KENNEDY)", "BRAZUELOS OCCIDENTAL (CIUDAD BOLIVAR)", "MONTEBLANCO (USME)", "VILLA CANDELARIA (CIUDAD BOLIVAR)", "MORAVIA (FONTIBON)", "SAN LUIS (RAFAEL URIBE URIBE)", "GRAN BRITALIA (KENNEDY)", "BOSA (BOSA)", "RINCON DE GALICIA (CIUDAD BOLIVAR)", "ALMIRANTE COLON (SUBA)", "TOCAREMA (KENNEDY)", "BOITA (KENNEDY)", "EL BOSQUE CENTRAL I (USME)", "AUTOPISTA MUZU ORIENTAL (PUENTE ARANDA)", "CATALINA II (KENNEDY)", "LA CATEDRAL (CANDELARIA)", "EL REDIL (USAQUEN)", "CORDILLERA DEL SUR (CIUDAD BOLIVAR)", "SAN CARLOS (TUNJUELITO)", "EL POA (SUBA)", "VEREDA SUBA NARANJOS (SUBA)", "GORGONZOLA (PUENTE ARANDA)", "ANTONIA SANTOS (BOSA)", "EL VERGEL ORIENTAL (KENNEDY)", "GARCES NAVAS (ENGATIVA)", "ALQUERIA LA FRAGUA NORTE (KENNEDY)", "SALAZAR GOMEZ (PUENTE ARANDA)", "LA HUERTA (USME)", "LA CECILIA (KENNEDY)", "PRIMAVERA OCCIDENTAL (PUENTE ARANDA)", "LOS OLIVARES (USME)", "EL PORTAL URBANO (USME)", "PALERMO SUR (RAFAEL URIBE URIBE)", "EL MOCHUELO URBANO (CIUDAD BOLIVAR)", "SANTA ISABEL SUR (LOS MARTIRES)", "MARCO FIDEL SUAREZ I (RAFAEL URIBE URIBE)", "ANDALUCIA II (BOSA)", "BRASIL (BOSA)", "SAN PEDRO DE LOS ROBLES (FONTIBON)", "YOMASA (SAN CRISTOBAL)", "SANTA BARBARA OCCIDENTAL (USAQUEN)", "CHICO NORTE (CHAPINERO)", "JARDIN BOTANICO (ENGATIVA)", "LA CAMELIA (PUENTE ARANDA)", "PUEBLO VIEJO (FONTIBON)", "ONCE DE NOVIEMBRE (BARRIOS UNIDOS)", "MODELIA (FONTIBON)", "PARQUE EL TUNAL (TUNJUELITO)", "VENECIA (TUNJUELITO)", "AURES II (SUBA)", "NUESTRA SENORA DEL ROSARIO (SUBA)", "SANTA LUCIA (RAFAEL URIBE URIBE)", "BRAVO PAEZ (RAFAEL URIBE URIBE)", "SANTA CECILIA PUENTE NORTE (USAQUEN)", "OLAYA (RAFAEL URIBE URIBE)", "QUIROGA CENTRAL (RAFAEL URIBE URIBE)", "CENTENARIO (RAFAEL URIBE URIBE)", "MURILLO TORO (RAFAEL URIBE URIBE)", "CHARCO URBANO (FONTIBON)", "TIHUAQUE (USME)", "LIBERTADOR (RAFAEL URIBE URIBE)", "HIPOTECHO (KENNEDY)", "DUITAMA (USME)", "SOTAVENTO (CIUDAD BOLIVAR)", "CONEJERA (SUBA)", "GALICIA (CIUDAD BOLIVAR)", "BARLOVENTO (CIUDAD BOLIVAR)", "LOS ALPES (SAN CRISTOBAL)", "LA TORRE (CIUDAD BOLIVAR)", "ATLANTA (CIUDAD BOLIVAR)", "ATENAS (SAN CRISTOBAL)", "LA PENA (SANTA FE)", "LOS LACHES (SANTA FE)", "EL CHANCO I (FONTIBON)", "PUERTA AL LLANO DE USME (USME)", "RONDA (CIUDAD BOLIVAR)", "ALTOS DEL ZUQUE (SAN CRISTOBAL)", "NUEVA YORK (KENNEDY)", "COLON (PUENTE ARANDA)", "LA AURORA (BARRIOS UNIDOS)", "EL NEVADO II (USME)", "JUAN XXIII (BARRIOS UNIDOS)", "EL RETIRO (CHAPINERO)", "LA SABANA (LOS MARTIRES)", "MARIA PAZ (KENNEDY)", "LAS MARGARITAS (USAQUEN)", "ACACIAS USAQUEN (USAQUEN)", "CIUDAD SALITRE NOR-ORIENTAL (TEUSAQUILLO)", "EL LISTON (LOS MARTIRES)", "GRANJAS DE SANTA SOFIA (RAFAEL URIBE URIBE)", "REMANSO (PUENTE ARANDA)", "CIUDAD HAYUELOS (FONTIBON)", "SAN FELIPE (BARRIOS UNIDOS)", "CORREDOR FERREO DEL SUR (PUENTE ARANDA)", "CIUDAD KENNEDY NORTE (KENNEDY)", "LA MERCED (SANTA FE)", "ESTACION CENTRAL (PUENTE ARANDA)", "SAMPER MENDOZA (LOS MARTIRES)", "QUINTA CAMACHO (CHAPINERO)", "CHUCUA DE LA VACA I (KENNEDY)", "LAS ORQUIDEAS (USAQUEN)", "GARCES NAVAS ORIENTAL (ENGATIVA)", "NUEVO TECHO (KENNEDY)", "MONTEVIDEO (FONTIBON)", "CASABLANCA SUBA URBANO (SUBA)", "NUEVA ZELANDIA (SUBA)", "VILLA ANNY II (BOSA)", "MAZUREN (SUBA)", "AGUAS CLARAS I (SAN CRISTOBAL)", "BELLAVISTA (CHAPINERO)", "PRIMAVERA (ENGATIVA)", "LA ESTANCIA (CIUDAD BOLIVAR)", "GALAN (PUENTE ARANDA)", "LOS ARRAYANES II (RAFAEL URIBE URIBE)", "SANTA MARIA (ENGATIVA)", "LA CAMPINA (KENNEDY)", "EL MOCHUELO (CIUDAD BOLIVAR)", "LAS FERIAS OCCIDENTAL (ENGATIVA)", "AUTOPISTA MEDELLIN (ENGATIVA)", "SAN JORGE SUR (RAFAEL URIBE URIBE)", "LA VICTORIA (SAN CRISTOBAL)", "RINCON DE LA VALVANERA (CIUDAD BOLIVAR)", "PRIMERO DE MAYO (SAN CRISTOBAL)", "OSPINA PEREZ SUR (PUENTE ARANDA)", "SANTA LIBRADA (USME)", "MARIA CANO (CIUDAD BOLIVAR)", "CLUB DE LOS LAGARTOS (SUBA)", "TTES DE COLOMBIA (SUBA)", "GUIPARMA (RAFAEL URIBE URIBE)", "EL CURUBO (USME)", "LOS TRES REYES I (CIUDAD BOLIVAR)", "VILLA DEL CERRO (SAN CRISTOBAL)", "AURES (SUBA)", "SANTA ROSA (SUBA)", "LA LIBERIA (USAQUEN)", "GRAN BRITALIA I (KENNEDY)", "RINCON DE SANTA INES (SUBA)", "VILLA DEL PRADO (SUBA)", "GRANADA NORTE (SUBA)", "BRITALIA (SUBA)", "VILLA NELLY III SECTOR (KENNEDY)", "CHUCUA DE LA VACA II (KENNEDY)", "POTOSI (CIUDAD BOLIVAR)", "VILLA DIANA (USME)", "BOSQUE CALDERON (CHAPINERO)", "MONACO (SUBA)", "MARIA CRISTINA (CHAPINERO)", "LA SALLE (CHAPINERO)", "LAS ACACIAS (CHAPINERO)", "TIBAQUE URBANO (SAN CRISTOBAL)", "PORVENIR (USME)", "SANTA CECILIA (ENGATIVA)", "VILLA ANNY I (BOSA)", "EL NUEVO PORTAL II RURAL (USME)", "LA ESPERANZA SUR I (USME)", "SIBERIA II (CHAPINERO)", "SIBERIA RURAL (CHAPINERO)", "EL CHARCO (FONTIBON)", "GALAN RURAL (KENNEDY)", "EL REFUGIO I (CHAPINERO)", "TUNDAMA (KENNEDY)", "CUNDINAMARCA (PUENTE ARANDA)", "EL MOCHUELO III URBANO (CIUDAD BOLIVAR)", "EL RINCON (SUBA)", "SAN CARLOS DE SUBA (SUBA)", "LAS BRISAS (CIUDAD BOLIVAR)", "EL DANUBIO AZUL (BOSA)", "GUAYMARAL (SUBA)", "QUIBA RURAL (CIUDAD BOLIVAR)", "LA UNION URBANO (SUMAPAZ)", "VILLA EMMA (BOSA)", "SAN FELIPE DE USME RURAL (USME)", "EL REFUGIO II (CHAPINERO)", "LA ESTRELLITA (USAQUEN)", "EL BOSQUE SUR ORIENTAL RURAL III (USME)", "TIBAQUE I (SAN CRISTOBAL)", "LAGUNITAS (CIUDAD BOLIVAR)", "TOCAIMITA ORIENTAL (USME)", "BARRANCAS ORIENTAL (USAQUEN)", "PUERTA AL LLANO RURAL (USME)", "SAN LUIS ALTOS DEL CABO (CHAPINERO)", "SAN ISIDRO RURAL (CHAPINERO)", "LAS ACACIAS RURAL (KENNEDY)", "INGEMAR I (CHAPINERO)", "SAN ISIDRO RURAL II (CHAPINERO)", "EL MOCHUELO II NORTE (CIUDAD BOLIVAR)", "SAN BERNARDINO XIX (BOSA)", "NUEVA ESPERANZA (CIUDAD BOLIVAR)", "EL MIRADOR II (CIUDAD BOLIVAR)", "CANAVERALEJO RURAL (BOSA)", "EL UVAL (USME)", "SAN JUAN URBANO (SUMAPAZ)", "PARAMO URBANO (CHAPINERO)", "PARAMO RURAL V (USAQUEN)", "EL TRIANGULO (SAN CRISTOBAL)", "TIBAQUE III (SAN CRISTOBAL)", "LA ESPERANZA (CHAPINERO)", "VEREDA EL TINTAL URBANO (KENNEDY)", "VEREDA EL TINTAL (FONTIBON)", "PENSILVANIA (PUENTE ARANDA)", "SAGRADO CORAZON (SANTA FE)", "CAOBOS SALAZAR (USAQUEN)", "VILLA HERMOSA (SUBA)", "ANTIGUO COUNTRY (CHAPINERO)", "USMINIA (USME)", "CANADA O GUIRA (SAN CRISTOBAL)", "LOS MOLINOS (RAFAEL URIBE URIBE)", "CANDELARIA LA NUEVA (CIUDAD BOLIVAR)", "MEXICO (CIUDAD BOLIVAR)", "SAN PEDRO (SUBA)", "LA GRANJA (ENGATIVA)", "NUEVO MUZU (TUNJUELITO)", "LA VALVANERA (CIUDAD BOLIVAR)", "SANTA MONICA (ENGATIVA)", "VILLA AMALIA (ENGATIVA)", "COMUNEROS (USME)", "SANTA CECILIA (FONTIBON)", "EL ENSUENO (CIUDAD BOLIVAR)", "DIANA TURBAY (RAFAEL URIBE URIBE)", "TOSCANA (SUBA)", "PORTALES DEL NORTE (SUBA)", "LA MARICHUELA (USME)", "CIUDADELA EL RECREO II (BOSA)", "LOS LAURELES SUR ORIENTAL I (SAN CRISTOBAL)", "LAS GUACAMAYAS III (SAN CRISTOBAL)", "SIBERIA URBANO (CHAPINERO)", "SANTA RITA DE SUBA (SUBA)", "LOS EJIDOS (PUENTE ARANDA)", "SABANA GRANDE (FONTIBON)", "SAN JUAN BAUTISTA (USME)", "TINTALITO (KENNEDY)", "CHICALA (BOSA)", "CHUCUA DE LA VACA III (KENNEDY)", "LA CABANA (BOSA)", "LA LIBERTAD (BOSA)", "DINTALITO (KENNEDY)", "LA GAITANA ORIENTAL (SUBA)", "EL CONTADOR (USAQUEN)", "SAN BERNARDINO POTRERITOS (BOSA)", "GRANADA (CHAPINERO)", "TUNA BAJA (SUBA)", "SANTA VIVIANA (CIUDAD BOLIVAR)", "SAN VICTORINO (LOS MARTIRES)", "QUINTA RAMOS (SAN CRISTOBAL)", "LA FISCALA (USME)", "LA MACARENA (SANTA FE)", "SANTA INES (SANTA FE)", "OLARTE (BOSA)", "COMUNEROS (PUENTE ARANDA)", "CEDRITOS (USAQUEN)", "ESPARTILLAL (CHAPINERO)", "ALCAZARES NORTE (BARRIOS UNIDOS)", "EL RUBI (KENNEDY)", "CALVO SUR (SAN CRISTOBAL)", "TIBABITA (USAQUEN)", "CASABLANCA SUBA URBANO II (SUBA)", "JIMENEZ DE QUESADA (BOSA)", "SAN VICENTE FERRER (TUNJUELITO)", "EL CARMEN (TUNJUELITO)", "TIMIZA C (KENNEDY)", "QUESADA (TEUSAQUILLO)", "ESCUELA DE CARABINEROS (SUBA)", "AUTOPISTA SUR (PUENTE ARANDA)", "JOSE JOAQUIN VARGAS (BARRIOS UNIDOS)", "DESARROLLO BRAZUELOS (USME)", "CEDRITOS DEL SUR (CIUDAD BOLIVAR)", "LAS FLORES (SUBA)", "EL CARMELO (KENNEDY)", "SAN FRANCISCO (CIUDAD BOLIVAR)", "SAN DIEGO-BOSA (BOSA)", "TIBABUYES II (SUBA)", "PRADO VERANIEGO SUR (SUBA)", "SALITRE SUBA (SUBA)", "RINCON DE SUBA (SUBA)", "SAN CRISTOBAL NORTE (USAQUEN)", "SAN JOSE DE BAVARIA (SUBA)", "INGLES (RAFAEL URIBE URIBE)", "CLARET (RAFAEL URIBE URIBE)", "VILLA MAYOR (RAFAEL URIBE URIBE)", "EL PLAYON (RAFAEL URIBE URIBE)", "SOSIEGO SUR (RAFAEL URIBE URIBE)", "SANTA INES SUR (SAN CRISTOBAL)", "BATAN (SUBA)", "NUEVA DELHI (SAN CRISTOBAL)", "SIETE DE AGOSTO (BARRIOS UNIDOS)", "COLOMBIA (BARRIOS UNIDOS)", "LA ESPERANZA SUR (FONTIBON)", "LA PICOTA ORIENTAL (RAFAEL URIBE URIBE)", "EL REFUGIO I (USME)", "GUADALUPE (CIUDAD BOLIVAR)", "OSPINA PEREZ (PUENTE ARANDA)", "EL RETAZO (BOSA)", "PROVIVIENDA ORIENTAL (KENNEDY)", "BOCHICA (PUENTE ARANDA)", "PROVIVIENDA (KENNEDY)", "LOS LIBERTADORES (SAN CRISTOBAL)", "TEJAR (PUENTE ARANDA)", "SAN GABRIEL NORTE (USAQUEN)", "PASADENA (SUBA)", "PARAMO URBANO I (USAQUEN)", "ESTORIL (SUBA)", "SAN GABRIEL NORTE II (USAQUEN)", "SANTA CECILIA DE SUBA I (SUBA)", "RINCON ALTAMAR (SUBA)", "NUEVA GRANADA BOSA (BOSA)", "QUINDIO (SAN CRISTOBAL)", "LA CONCORDIA (CANDELARIA)", "VERACRUZ (SANTA FE)", "ARBOLEDA SANTA TERESITA (SAN CRISTOBAL)", "EL MIRADOR (CIUDAD BOLIVAR)", "EL LAUREL (ENGATIVA)", "VILLA CARMENZA (FONTIBON)", "EL ENCANTO (ENGATIVA)", "SIMON BOLIVAR (BARRIOS UNIDOS)", "LA CAROLINA (USAQUEN)", "EL NOGAL (CHAPINERO)", "EGIPTO (CANDELARIA)", "BOSQUE DE MODELIA (FONTIBON)", "EL VERVENAL (USAQUEN)", "SAN ANTONIO NOROCCIDENTAL (USAQUEN)", "EL CEREZO (USAQUEN)", "EL TOBERIN (USAQUEN)", "LA CITA (USAQUEN)", "EL GACO (ENGATIVA)", "EL MADRIGAL (ENGATIVA)", "LA MAGDALENA (KENNEDY)", "LA ESPERANZA SUR (USME)", "ARBORIZADORA BAJA (CIUDAD BOLIVAR)", "CIUDAD HUNZA (SUBA)", "SABANA DE TIBABUYES (SUBA)", "REMANSO URBANO (BOSA)", "TORCA I (USAQUEN)", "LA RIVIERA (ENGATIVA)", "MOLINOS NORTE (USAQUEN)", "GUADUAL FONTIBON (FONTIBON)", "JORGE URIBE BOTERO (KENNEDY)", "OSORIO X URBANO (BOSA)", "LA ESPERANZA (BARRIOS UNIDOS)", "TOCAIMITA ORIENTAL I (USME)", "ENTRERIOS (BARRIOS UNIDOS)", "CIUDAD KENNEDY (KENNEDY)", "LA BELLEZA (SAN CRISTOBAL)", "EL PARAISO (CHAPINERO)", "QUIBA URBANO (CIUDAD BOLIVAR)", "EL PORTAL DEL BRASIL (BOSA)", "MIRADOR DEL NORTE (USAQUEN)", "PROVIVIENDA NORTE (PUENTE ARANDA)", "NACIONES UNIDAS (CIUDAD BOLIVAR)", "LA PAZ BOSA (BOSA)", "LA ALAMEDA (SANTA FE)", "JACQUELINE (KENNEDY)", "LAS NIEVES (SANTA FE)", "SAN PABLO JERICO (FONTIBON)", "LA MERCED NORTE (BARRIOS UNIDOS)", "SAMORE (TUNJUELITO)", "TUNAL ORIENTAL (TUNJUELITO)", "LA ORQUIDEA DE USME (USME)", "MUZU (TUNJUELITO)", "CIUDAD BOLIVAR (CIUDAD BOLIVAR)", "EL EJIDO (PUENTE ARANDA)", "QUINTA PAREDES (TEUSAQUILLO)", "MARLY (CHAPINERO)", "QUIRIGUA II (ENGATIVA)", "LA FAENA (ENGATIVA)", "DIANA TURBAY ARRAYANES (RAFAEL URIBE URIBE)", "BELLAVISTA SUR (SAN CRISTOBAL)", "GRANADA SUR (SAN CRISTOBAL)", "COSTA AZUL (SUBA)", "CANAIMA (USAQUEN)", "LA URIBE (USAQUEN)", "BOSQUE DE PINOS I (USAQUEN)", "LA ESTRELLITA III (USAQUEN)", "ESTRELLA DEL NORTE (USAQUEN)", "SAN ANTONIO NORTE (USAQUEN)", "SALAZAR USME (USME)", "SUMAPAZ (CIUDAD BOLIVAR)", "SAN PEDRO SUR (USME)", "SAN IGNACIO (ENGATIVA)", "SAN ANTONIO ENGATIVA (ENGATIVA)", "CIUDADELA COLSUBSIDIO (ENGATIVA)", "LOS NARANJOS (SUBA)", "CARACOLI (CIUDAD BOLIVAR)", "SAN DIEGO (SANTA FE)", "CENTRAL DE MEZCLAS (CIUDAD BOLIVAR)", "LA CHUCUA (SUBA)", "LAS AGUAS (CANDELARIA)", "BOSQUE IZQUIERDO (SANTA FE)", "LA CABANA (ENGATIVA)", "LA PATRIA (BARRIOS UNIDOS)", "SAN FERNANDO OCCIDENTAL (BARRIOS UNIDOS)", "ZONA FRANCA (FONTIBON)", "RAMIREZ (SANTA FE)", "POLO CLUB (BARRIOS UNIDOS)", "SAN RAFAEL (CIUDAD BOLIVAR)", "EL CHICO (CHAPINERO)", "SALITRE OCCIDENTAL (FONTIBON)", "PARDO RUBIO (CHAPINERO)", "TERMINAL DE TRANSPORTES (FONTIBON)", "RAFAEL URIBE (BARRIOS UNIDOS)", "PINOS DE LOMBARDIA (SUBA)", "LA TRINIDAD (PUENTE ARANDA)", "LA ESTRELLITA I (USAQUEN)", "PARIS (ENGATIVA)", "EL PEDREGAL (USME)", "KASANDRA (FONTIBON)", "BOYACA (ENGATIVA)", "SAN LUIS (TEUSAQUILLO)", "PARQUE NACIONAL URBANO (CANDELARIA)", "BENJAMIN HERRERA (BARRIOS UNIDOS)", "FRANCO (FONTIBON)", "JIMENEZ DE QUESADA II SECTOR (BOSA)", "LA PAZ (RAFAEL URIBE URIBE)", "ARABIA (CIUDAD BOLIVAR)", "BOSQUE DE LOS ALPES (SAN CRISTOBAL)", "EL ROCIO (SANTA FE)", "CIUDAD KENNEDY OCCIDENTAL (KENNEDY)", "VILLA GLORIA (CIUDAD BOLIVAR)", "BARRANQUILLITA (USME)", "GALERIAS (TEUSAQUILLO)", "SUBA CERROS (SUBA)", "PRADO PINZON (SUBA)", "LOS CEDROS (USAQUEN)", "MONTES (PUENTE ARANDA)", "RENANIA URAPANES (KENNEDY)", "ESCUELA MILITAR (BARRIOS UNIDOS)", "BUENAVISTA (USAQUEN)", "METROPOLIS (BARRIOS UNIDOS)", "LA ESTRADA (ENGATIVA)", "TIBABITA I (USAQUEN)", "VERBENAL SAN ANTONIO (USAQUEN)", "LA PRIMAVERA I (CIUDAD BOLIVAR)", "BARRANCAS NORTE (USAQUEN)", "VILLAS DE ALCALA (ENGATIVA)", "CEDRO SALAZAR (USAQUEN)", "BARRANCAS (USAQUEN)", "JUAN REY SUR (USME)", "EL GUAVIO (SANTA FE)", "SANTA ISABEL (LOS MARTIRES)", "MILLAN (CIUDAD BOLIVAR)", "QUINTA MUTIS (BARRIOS UNIDOS)", "ISLANDIA (BOSA)", "LA ANDREA (USME)", "EL RINCON NORTE (SUBA)", "EL NUEVO PORTAL (USME)", "ESPINO I (CIUDAD BOLIVAR)", "TIMIZA B (KENNEDY)", "SAN EUSEBIO (PUENTE ARANDA)", "CIUDAD SALITRE SUR-ORIENTAL (TEUSAQUILLO)", "SAN CAYETANO (SUBA)", "SAN JOSE DEL PRADO (SUBA)", "EL REFUGIO (CHAPINERO)", "ALTOS DEL ZIPA (SAN CRISTOBAL)", "BOSQUE DE PINOS III (USAQUEN)", "LOS ROSALES (CHAPINERO)", "MIRANDELA (SUBA)", "BOSQUE DE PINOS (USAQUEN)", "LOS SAUCES (BOSA)", "SAN PEDRO (BOSA)", "CENTRO ADMINISTRATIVO (CANDELARIA)", "LA FAVORITA (LOS MARTIRES)", "BARCELONA (PUENTE ARANDA)", "VILLA GLADYS (ENGATIVA)", "LAS NAVETAS (FONTIBON)", "PATIO BONITO (KENNEDY)", "QUIRIGUA ORIENTAL (ENGATIVA)", "SAN ANTONIO DEL MIRADOR (CIUDAD BOLIVAR)", "CHICO SUR (BOSA)", "PARQUE POPULAR SALITRE (BARRIOS UNIDOS)", "SABANA DE TIBABUYES NORTE (SUBA)", "LA FLORIDA OCCIDENTAL (PUENTE ARANDA)", "VILLA LUZ (ENGATIVA)", "BILBAO (SUBA)", "EL PLAN (SUBA)", "LA SERENA (ENGATIVA)", "NORMANDIA OCCIDENTAL (ENGATIVA)", "RAFAEL ESCAMILLA (CIUDAD BOLIVAR)", "VEREDA SUBA CERROS II (SUBA)", "MONTEBELLO (SAN CRISTOBAL)", "MADELENA (CIUDAD BOLIVAR)", "LUSITANIA (KENNEDY)", "EL BOSQUE (USME)", "SIERRA MORENA II (CIUDAD BOLIVAR)", "QUINTAS DEL SUR (CIUDAD BOLIVAR)", "SAN BERNARDINO XXV URBANO (BOSA)", "LAS MERCEDES I (SUBA)", "EL CORTIJO (ENGATIVA)", "ESTRELLA (TEUSAQUILLO)", "ALFONSO LOPEZ (TEUSAQUILLO)", "SAN BERNARDINO XXII URBANO (BOSA)", "MODELO SUR (SAN CRISTOBAL)", "USATAMA (LOS MARTIRES)", "INGEMAR (CHAPINERO)", "BOSA NOVA (BOSA)", "SABANA DEL DORADO (ENGATIVA)", "SANTA TERESA (USAQUEN)", "LA CAMELIA II (PUENTE ARANDA)", "LAS MARGARITAS (BOSA)", "EL CORZO I (BOSA)", "EL MIRADOR DE LA ESTANCIA (CIUDAD BOLIVAR)", "CATALUNA (CHAPINERO)", "FLORIDA (TEUSAQUILLO)", "LOS ALPES SUR (CIUDAD BOLIVAR)", "SAN GABRIEL (PUENTE ARANDA)", "PARQUE NACIONAL (SANTA FE)", "PASTRANA (KENNEDY)", "EL PENON DEL CORTIJO (CIUDAD BOLIVAR)", "CLASS (KENNEDY)", "BELEN (CANDELARIA)", "LAS MARGARITAS (KENNEDY)", "VILLA ALSACIA (KENNEDY)", "EL ROCIO NORTE (USAQUEN)", "ARBOLEDA SUR (RAFAEL URIBE URIBE)", "LOS ALMENDROS (KENNEDY)", "CIUDAD DE CALI (KENNEDY)", "INDUSTRIAL CENTENARIO (PUENTE ARANDA)", "LAS ACACIAS (KENNEDY)", "CALANDAIMA (KENNEDY)", "BELLAVISTA (CIUDAD BOLIVAR)", "EL RECUERDO (TEUSAQUILLO)", "LA SOLEDAD (TEUSAQUILLO)", "BELALCAZAR (TEUSAQUILLO)", "FATIMA (TUNJUELITO)", "EL PARAISO (KENNEDY)", "BRASILIA (BOSA)", "EL MUELLE (ENGATIVA)", "CORABASTOS (KENNEDY)", "LAS GUACAMAYAS IV (SAN CRISTOBAL)", "JORGE GAITAN CORTES (PUENTE ARANDA)", "LA ESTRADITA (ENGATIVA)", "ALAMOS (ENGATIVA)", "PARIS GAITAN (ENGATIVA)", "CENTRO INDUSTRIAL (PUENTE ARANDA)", "NIZA NORTE (SUBA)", "JUAN JOSE RONDON I (USME)", "EL TINTAL II (FONTIBON)", "FLORENCIA (ENGATIVA)", "LA AURORA (USME)", "NUEVO SAN ANDRES (USME)", "TUNA ALTA (SUBA)", "CANODROMO (SUBA)", "VILLA ELISA (SUBA)", "SAN JOSE SUR ORIENTAL (SAN CRISTOBAL)", "ARBORIZADORA ALTA  II (CIUDAD BOLIVAR)", "EL MOCHUELO ALTO (CIUDAD BOLIVAR)", "LOS TRES REYES (CIUDAD BOLIVAR)", "TIBABUYES UNIVERSAL (SUBA)", "ALTOS DE CHOZICA (SUBA)", "PUERTA DE TEJA (FONTIBON)", "VERGEL OCCIDENTAL (KENNEDY)", "SANTA HELENITA (ENGATIVA)", "SANTA HELENA (SUBA)", "CIUDAD LONDRES I (SAN CRISTOBAL)", "GIBRALTAR SUR (CIUDAD BOLIVAR)", "EL CARMEN FONTIBON (FONTIBON)", "VELODROMO (SAN CRISTOBAL)", "BOSA NOVA EL PORVENIR (BOSA)", "CENTRO USME RURAL (USME)", "EL TOLDO (SUMAPAZ)", "SAN ANTONIO (SUMAPAZ)", "EL CORZO RURAL (BOSA)", "SAN JOSE (SUMAPAZ)", "ARABIA 1 (CIUDAD BOLIVAR)", "LA MAGDALENA I (KENNEDY)", "OSORIO IV (KENNEDY)", "LAS DELICIAS DEL CARMEN II SECTOR (USAQUEN)", "RAIZAL (SUMAPAZ)", "PEPINITOS (USME)", "TUNAL BAJO (SUMAPAZ)", "SAN BENITO (USME)", "CHISACA (USME)", "TIHUAQUE RURAL (USME)", "NUEVA GRANADA (SUMAPAZ)", "CONCEPCION (SUMAPAZ)", "LA REQUILINA RURAL II (USME)", "OSORIO X (BOSA)", "EL TINTAL (FONTIBON)", "LAS GUACAMAYAS II (SAN CRISTOBAL)", "PUERTO RICO (RAFAEL URIBE URIBE)", "NARINO SUR (SAN CRISTOBAL)", "VILLA DEL MAR (ENGATIVA)", "CIUDAD BACHUE II (ENGATIVA)", "BELEN FONTIBON (FONTIBON)", "EL MINUTO DE MARIA (CIUDAD BOLIVAR)", "BELLA FLOR (CIUDAD BOLIVAR)", "LA GIRALDA (FONTIBON)", "YOMASA NORTE (USME)", "NIZA SUBA (SUBA)", "AUTOPISTA MUZU (PUENTE ARANDA)", "JORGE ELIECER GAITAN (BARRIOS UNIDOS)", "ESCUELA DE CABALLERIA II (USAQUEN)", "CENTRO USME RURAL II (USME)", "LA UNION (USME)", "SANTO DOMINGO (SUMAPAZ)", "PARAMO II RURAL (USAQUEN)", "TUNAL ALTO (SUMAPAZ)", "CENTRO USME RURAL I (USME)", "SAN BERNARDINO XXV (BOSA)", "LAS ANIMAS (SUMAPAZ)", "TUNA RURAL (SUBA)", "EL UVAL RURAL (USME)", "EL TABACO (SUMAPAZ)", "EL MOCHUELO II (CIUDAD BOLIVAR)", "MOLINO RURAL (SAN CRISTOBAL)", "LOS RIOS (SUMAPAZ)", "LAGUNITAS (SUMAPAZ)", "CHORRERAS (SUMAPAZ)", "LA LOMITA (SUBA)", "TIBAQUE SUR (USME)", "PARAMO IV (CHAPINERO)", "SAN LUIS ALTOS DEL CABO RURAL II (CHAPINERO)", "TIBAQUE II (USME)", "CENTRO USME (USME)", "SAN ISIDRO (CHAPINERO)", "MOCHUELO ALTO URBANO (CIUDAD BOLIVAR)", "LAS VEGAS (SUMAPAZ)", "LA ARBOLEDA RURAL (SAN CRISTOBAL)", "LAS VIOLETAS RURAL (USME)", "LAS MERCEDES (CIUDAD BOLIVAR)", "PASQUILLITA (CIUDAD BOLIVAR)", "PENALISA (SUMAPAZ)", "EL BOSQUE CENTRAL (USME)", "CHIGUAZA RURAL (USME)", "EL BOSQUE SUR ORIENTAL RURAL I (USME)", "TIBABITA RURAL I (USAQUEN)", "CASABLANCA SUBA II (SUBA)", "EL MOCHUELO IV (CIUDAD BOLIVAR)", "TOCAIMITA SUR (USME)", "EL CHANCO RURAL III (FONTIBON)", "EL CHANCO RURAL II (FONTIBON)", "INGEMAR ORIENTAL RURAL (CHAPINERO)", "LA REQUILINA RURAL (USME)", "MOCHUELO ALTO RURAL (CIUDAD BOLIVAR)", "BOSQUE DE PINOS III RURAL (USAQUEN)", "EL CHANCO II (FONTIBON)", "CAMPO VERDE (BOSA)", "EL REMANSO (BOSA)", "BARAJAS NORTE (SUBA)", "TIBABITA RURAL (USAQUEN)", "TORCA RURAL I (USAQUEN)", "PARAMO I RURAL (CHAPINERO)", "PARAMO (USAQUEN)", "TORCA RURAL II (USAQUEN)", "PARAMO I (CHAPINERO)", "SANTA ROSA ALTA (SUMAPAZ)", "PARQUE NACIONAL ORIENTAL (SANTA FE)", "OSORIO XXIII (BOSA)", "CIUDAD LONDRES RURAL (USME)", "BETANIA (SUMAPAZ)", "LAS SOPAS (SUMAPAZ)", "BRAZUELOS OCCIDENTAL RURAL (CIUDAD BOLIVAR)", "PORTAL RURAL II (USME)", "EL ITSMO (SUMAPAZ)", "LAGUNA VERDE (SUMAPAZ)", "CHARCO RURAL (FONTIBON)", "BARRANCAS ORIENTAL RURAL (USAQUEN)", "SANTA ROSA (CIUDAD BOLIVAR)", "CURUBITAL (USME)", "ENGATIVA EL DORADO (ENGATIVA)", "LA UNION (SUMAPAZ)", "OLARTE (USME)", "SANTA ROSA BAJA (SUMAPAZ)", "TAQUECITOS (SUMAPAZ)", "HOYA TEUSACA (SANTA FE)", "EL MOCHUELO III (CIUDAD BOLIVAR)", "CIUDAD BOLIVAR RURAL I (CIUDAD BOLIVAR)", "PARAMO III RURAL (USAQUEN)", "HOYA SAN CRISTOBAL (SAN CRISTOBAL)", "LA REGADERA (USME)", "LAS MARGARITAS (USME)", "EL HATO (USME)", "SIBERIA (CHAPINERO)", "TIBAQUE (SAN CRISTOBAL)", "NAZARETH (SUMAPAZ)", "VEREDA EL TINTAL RURAL (KENNEDY)", "EL PANTANO (ENGATIVA)", "ARRAYAN (USME)", "LOS ANDES (USME)", "QUIBA ALTO (CIUDAD BOLIVAR)", "CASABLANCA SUBA I (SUBA)", "LILIANA (USME)", "LAS MERCEDES SUBA RURAL (SUBA)", "EL BOSQUE SUR ORIENTAL (USME)", "SANTA BARBARA (CIUDAD BOLIVAR)", "EL PORVENIR DE LOS SOCHES (USME)", "EL MOCHUELO II URBANO (CIUDAD BOLIVAR)", "SAN PABLO BOSA (BOSA)", "LOS SOCHES (USME)", "EL NEVADO (USME)", "ALTOS DEL POBLADO (SAN CRISTOBAL)", "LA GLORIA OCCIDENTAL (SAN CRISTOBAL)", "EDUARDO SANTOS (LOS MARTIRES)", "ALASKA (USME)", "LAGO GAITAN (CHAPINERO)", "LA PAMPA (KENNEDY)", "PRIMAVERA II (CIUDAD BOLIVAR)", "SANTA LIBRADA NORTE (USME)", "TORCA II (USAQUEN)", "OSORIO II (KENNEDY)", "CIUDAD BOLIVAR RURAL III (CIUDAD BOLIVAR)", "PARAMO II (CHAPINERO)", "SAN JUAN (SUMAPAZ)", "SAN PEDRO (FONTIBON)", "CAPITOLIO (SUMAPAZ)", "QUIBA BAJO (CIUDAD BOLIVAR)", "LAS PALMAS (SUMAPAZ)", "LAS AURAS (SUMAPAZ)", "INGEMAR ORIENTAL I (CHAPINERO)", "PARDO RUBIO I (CHAPINERO)", "LA PERSEVERANCIA I (SANTA FE)", "NAZARETH URBANO (SUMAPAZ)", "AGUAS CLARAS (SAN CRISTOBAL)", "ESCUELA DE INFANTERIA (USAQUEN)", "LA PRADERA NORTE (USAQUEN)", "VILLAS DE GRANADA (ENGATIVA)", "DELMONTE (SUBA)", "ESCUELA DE CABALLERIA I (USAQUEN)", "CASTILLA (KENNEDY)", "SANTA ANA (USAQUEN)", "SAN FRANCISCO RURAL (SANTA FE)", "EL PROGRESO USME (USME)", "LA CANDELARIA (SUBA)", "SAN RAFAEL INDUSTRIAL (PUENTE ARANDA)", "BAQUERO (BARRIOS UNIDOS)", "PIO XII (KENNEDY)", "SANTIAGO PEREZ (RAFAEL URIBE URIBE)", "PAULO VI (TEUSAQUILLO)", "CHAPINERO NORTE (CHAPINERO)", "SAN ANTONIO URBANO (ENGATIVA)", "LA ESTACION BOSA (BOSA)", "SANTA BARBARA CENTRAL (USAQUEN)", "VILLA ISRAEL (USME)", "BOSQUE POPULAR (ENGATIVA)", "CATALINA (KENNEDY)", "CIUDAD KENNEDY SUR (KENNEDY)", "EL PORTAL DEL DIVINO (USME)", "HORIZONTES NORTE (USAQUEN)", "SAN FERNANDO (BARRIOS UNIDOS)", "PARQUE DISTRITAL SALITRE (BARRIOS UNIDOS)", "SAN VICENTE (SAN CRISTOBAL)", "SAN FRANCISCO (PUENTE ARANDA)", "DANUBIO II (USME)", "LA PAZ (BARRIOS UNIDOS)", "MUEQUETA (BARRIOS UNIDOS)", "VILLEMAR (FONTIBON)", "SANTA TERESA DE SUBA (SUBA)", "CASA BLANCA SUBA I (SUBA)", "SANTA FE (LOS MARTIRES)", "SIBERIA CENTRAL (CHAPINERO)", "VOTO NACIONAL (LOS MARTIRES)", "MORALBA (SAN CRISTOBAL)", "ISMAEL PERDOMO (CIUDAD BOLIVAR)", "LAS BRISAS (SAN CRISTOBAL)", "LAS FERIAS (ENGATIVA)", "VILLAS EL DIAMANTE (CIUDAD BOLIVAR)", "ARRAYANES VI (USME)", "QUIRIGUA I (ENGATIVA)", "PALO BLANCO (ENGATIVA)", "SAN BERNARDINO I (BOSA)", "EL VIRREY (USME)", "MONTE CARLO (SAN CRISTOBAL)", "CASA DE TEJA (CIUDAD BOLIVAR)", "DIANA TURBAY CULTIVOS (RAFAEL URIBE URIBE)", "INTERINDUSTRIAL (FONTIBON)", "CASABLANCA SUBA URBANO I (SUBA)", "HIPOTECHO SUR (KENNEDY)", "EL VERGEL (FONTIBON)", "SAN BLAS II (SAN CRISTOBAL)", "SEGUNDO CONTADOR (USAQUEN)", "OSORIO III (KENNEDY)", "LA CORUNA (CIUDAD BOLIVAR)", "GUALOCHE (BOSA)", "CASA BLANCA SUR (KENNEDY)", "LAS LOMAS (SAN CRISTOBAL)", "SURAMERICA (SAN CRISTOBAL)", "LA ESPERANZA DE USME (USME)", "TIMIZA A (KENNEDY)", "EL ROSARIO (BARRIOS UNIDOS)", "NORMANDIA (ENGATIVA)", "EL TESORO (CIUDAD BOLIVAR)", "VILLA DEL RIO (BOSA)", "SANTA SOFIA (BARRIOS UNIDOS)", "EL DORADO INDUSTRIAL (ENGATIVA)", "LA LAGUNA FONTIBON (FONTIBON)", "SANTA INES SUR II (SAN CRISTOBAL)", "LA CABRERA (CHAPINERO)", "SAN JOSE DE USAQUEN (USAQUEN)", "QUIBA I (CIUDAD BOLIVAR)", "SAUCEDAL (KENNEDY)", "RAMAJAL (SAN CRISTOBAL)", "TEUSAQUILLO (TEUSAQUILLO)", "LAS GUACAMAYAS I (SAN CRISTOBAL)", "SAN ANTONIO (BOSA)", "SANTA FE BOSA (BOSA)", "BATALLON CALDAS (PUENTE ARANDA)", "EL DORADO (ENGATIVA)", "LLANO GRANDE (KENNEDY)", "SANTA TERESITA (TEUSAQUILLO)", "CONCEPCION NORTE (BARRIOS UNIDOS)", "ARMENIA (TEUSAQUILLO)", "PABLO VI NORTE (TEUSAQUILLO)", "GIRARDOT (SANTA FE)", "SAN BERNARDO (SANTA FE)", "QUIROGA SUR (RAFAEL URIBE URIBE)", "PARCELA EL PORVENIR (BOSA)", "LOS CEDROS ORIENTAL (USAQUEN)", "JUAN REY (LA PAZ) (SAN CRISTOBAL)", "GINEBRA (USAQUEN)", "ATENAS (SUBA)", "CEDRO NARVAEZ (USAQUEN)", "VILLA MARIA I (SUBA)", "LA GAITANA (SUBA)", "HIPOTECHO OCCIDENTAL (KENNEDY)", "TINTALA (KENNEDY)", "BOCHICA II (ENGATIVA)", "EL SALITRE (TEUSAQUILLO)", "QUIROGA (RAFAEL URIBE URIBE)", "HOSPITAL SAN CARLOS (RAFAEL URIBE URIBE)", "EL CHIRCAL SUR (CIUDAD BOLIVAR)", "MARCO FIDEL SUAREZ (RAFAEL URIBE URIBE)", "RINCON DEL CHICO (USAQUEN)", "TUNJUELITO (USME)", "SANTA BARBARA ORIENTAL (USAQUEN)", "TIBABUYES OCCIDENTAL (SUBA)", "LA REQUILINA (USME)", "SUBA URBANO (SUBA)", "VILLA ALCAZAR (SUBA)", "CIUDAD BACHUE (ENGATIVA)", "ARBORIZADORA ALTA I (CIUDAD BOLIVAR)", "LA ALAMEDA (CIUDAD BOLIVAR)", "LUCERO DEL SUR (CIUDAD BOLIVAR)", "EL PINAR (SAN CRISTOBAL)", "LA GLORIA ORIENTAL (SAN CRISTOBAL)", "BELLA SUIZA (USAQUEN)", "CIUDAD JARDIN NORTE (SUBA)", "PARAISO QUIBA (CIUDAD BOLIVAR)", "CALLEJON SANTA BARBARA (RAFAEL URIBE URIBE)", "FERROCAJA FONTIBON (FONTIBON)", "VENECIA OCCIDENTAL (TUNJUELITO)", "PORCIUNCULA (CHAPINERO)", "FISCALA ALTA (USME)", "CENTRO USME URBANO (USME)", "LA FISCALA NORTE (USME)", "EL TUNO (USME)", "JUAN JOSE RONDON (CIUDAD BOLIVAR)", "CIUDAD KENNEDY CENTRAL (KENNEDY)", "EL PARAISO (SAN CRISTOBAL)", "BETANIA (BOSA)", "LA VEGA SAN BERNARDINO (BOSA)", "GALAN (KENNEDY)", "MARSELLA (KENNEDY)", "CHARLES DE GAULLE (BOSA)", "SANTA RITA SUR ORIENTAL (SAN CRISTOBAL)", "CAMPO HERMOSO (KENNEDY)", "AREA ARTILLERIA (TUNJUELITO)", "SAN JOSE V SECTOR (SUBA)", "CARMEN DEL SOL (RAFAEL URIBE URIBE)", "PUENTE COLORADO (SAN CRISTOBAL)", "NUEVA GLORIA (SAN CRISTOBAL)", "PUENTE ARANDA (PUENTE ARANDA)", "BANCO CENTRAL (TEUSAQUILLO)", "EL SATELITE (CIUDAD BOLIVAR)", "BOLIVIA ORIENTAL (ENGATIVA)", "SAN RAFAEL USME (SAN CRISTOBAL)", "CAMPANELLA (SUBA)", "SAN AGUSTIN (RAFAEL URIBE URIBE)", "SAN FELIPE DE USME (USME)", "LA ESTANZUELA (LOS MARTIRES)", "VITELMA (SAN CRISTOBAL)", "SANTA BARBARA (CANDELARIA)", "LAS GAVIOTAS (SAN CRISTOBAL)", "LA CAROLINA DE SUBA (SUBA)", "EL PINO (SUBA)", "JUAN PABLO II (CIUDAD BOLIVAR)", "BELLO HORIZONTE (SAN CRISTOBAL)", "LUCERO ALTO (CIUDAD BOLIVAR)", "MEISSEN (CIUDAD BOLIVAR)", "BRISAS DEL VOLADOR (CIUDAD BOLIVAR)", "CHICO NORTE III SECTOR (CHAPINERO)", "CIUDAD UNIVERSITARIA (TEUSAQUILLO)", "EL PARAISO BOSA (KENNEDY)", "LISBOA (USAQUEN)", "SANTA BIBIANA (USAQUEN)", "SANTA ANA OCCIDENTAL (USAQUEN)", "CENTRO ADMINISTRATIVO OCC. (TEUSAQUILLO)", "VILLA DE LOS ALPES I (SAN CRISTOBAL)", "LA MARIA (SAN CRISTOBAL)", "GILMAR (SUBA)", "LAGO DE SUBA (SUBA)", "LAS VILLAS (SUBA)", "LISBOA (SUBA)", "PUENTE LARGO (SUBA)", "FLORIDA BLANCA (ENGATIVA)", "EL REMANSO I (BOSA)", "CHAPINERO OCCIDENTAL (TEUSAQUILLO)", "GRAN GRANADA (ENGATIVA)", "IRAGUA (SUBA)", "LUIS CARLOS GALAN (ENGATIVA)", "EMAUS (CHAPINERO)", "MARANDU (ENGATIVA)", "LA ESMERALDA (TEUSAQUILLO)", "CAMPIN (TEUSAQUILLO)", "LA REFORMA (USME)", "ARRAYANES V (USME)", "SANTA ANA SUR (SAN CRISTOBAL)", "PASO ANCHO (BOSA)", "LA CASTELLANA (BARRIOS UNIDOS)", "LAS DELICIAS (KENNEDY)", "ABRAHAM LINCOLN (TUNJUELITO)", "VILLAS DE GRANADA I (ENGATIVA)", "PALERMO (TEUSAQUILLO)", "LAS DOS AVENIDAS (KENNEDY)", "VILLA DE LOS ALPES (SAN CRISTOBAL)", "BOSQUES DE SAN JORGE (SUBA)", "TECHO (KENNEDY)", "LAS MERCEDES (SAN CRISTOBAL)", "RIONEGRO (BARRIOS UNIDOS)", "COUNTRY CLUB (USAQUEN)", "LA CALLEJA (USAQUEN)", "CENTRO ENGATIVA II (ENGATIVA)", "TIBANA (PUENTE ARANDA)", "SANTA CATALINA (KENNEDY)", "VEINTE DE JULIO (SAN CRISTOBAL)", "GRANJAS SAN PABLO (RAFAEL URIBE URIBE)", "GINEBRA II (USAQUEN)", "JULIO FLOREZ (SUBA)", "MANDALAY (KENNEDY)", "PUENTE GRANDE (FONTIBON)", "GRANADA SUR (USME)", "ANDES NORTE (SUBA)", "LOURDES (SANTA FE)", "QUIBA (CIUDAD BOLIVAR)", "LA ASUNCION (PUENTE ARANDA)", "LAS VIOLETAS (USME)", "PRADO VERANIEGO (SUBA)", "SANTO DOMINGO (CIUDAD BOLIVAR)", "MODELIA OCCIDENTAL (FONTIBON)", "ENGATIVA ZONA URBANA (ENGATIVA)", "EL TINTAL III (KENNEDY)", "BARCELONA SUR (SAN CRISTOBAL)", "GUSTAVO RESTREPO (RAFAEL URIBE URIBE)", "ISLA DEL SOL (TUNJUELITO)", "LA COMUNA (USME)", "ARGELIA II (BOSA)", "SERRANIAS (USME)", "LA RESURRECCION (RAFAEL URIBE URIBE)", "ANTONIO JOSE DE SUCRE (USME)", "RICAURTE (LOS MARTIRES)", "LA RESURRECCION I (RAFAEL URIBE URIBE)", "CENTRO NARINO (TEUSAQUILLO)", "ALTOS DE SUBA (SUBA)", "JERUSALEN (CIUDAD BOLIVAR)", "DONA LILIANA (USME)", "BONANZA (ENGATIVA)", "POTOSI (SUBA)", "NIZA SUR (SUBA)", "GRANJAS DE TECHO (FONTIBON)", "LA PRADERA (CIUDAD BOLIVAR)", "LOS LAURELES II (CIUDAD BOLIVAR)", "JUAN XXIII (CHAPINERO)", "CORDOBA (SAN CRISTOBAL)", "JOSE ANTONIO GALAN (BOSA)", "EL PROGRESO (LOS MARTIRES)", "LAS ACACIAS (CIUDAD BOLIVAR)", "QUIROGA I (RAFAEL URIBE URIBE)", "LA GRANJA NORTE (USAQUEN)", "LAGUNITAS URBANO (CIUDAD BOLIVAR)", "ALQUERIA LA FRAGUA (KENNEDY)", "EL DORADO (SANTA FE)", "ALCALA (PUENTE ARANDA)", "LAS AMERICAS (TEUSAQUILLO)", "SUCRE (CHAPINERO)", "ACEVEDO TEJADA (TEUSAQUILLO)", "EL MOCHUELO ORIENTAL (USME)", "EL VERGEL (LOS MARTIRES)", "VERONA (CIUDAD BOLIVAR)", "LA INDEPENDENCIA (BOSA)", "RAFAEL NUNEZ (TEUSAQUILLO)", "ALQUERIA LA FRAGUA II (KENNEDY)", "VILLAS DEL PROGRESO (BOSA)", "CASABLANCA (KENNEDY)", "TAIRONA (KENNEDY)", "VALLADOLID (KENNEDY)", "LA CAPUCHINA (SANTA FE)", "VILLABEL (SAN CRISTOBAL)", "SAN MARTIN (BOSA)", "LA MAGDALENA (TEUSAQUILLO)", "MOLINOS DE ORIENTE (SAN CRISTOBAL)", "CIUDAD BACHUE I ETAPA (ENGATIVA)", "SAN CRISTOBAL SUR (SAN CRISTOBAL)", "BELLAVISTA LUCERO ALTO (CIUDAD BOLIVAR)", "CHICO NORTE II SECTOR (CHAPINERO)", "GARCES NAVAS SUR (ENGATIVA)", "BOCHICA (ENGATIVA)", "DANUBIO (USME)", "LECH WALESA (SUBA)", "LA PRADERA (PUENTE ARANDA)", "ESCUELA GENERAL SANTANDER (TUNJUELITO)", "CHIGUAZA URBANO (SAN CRISTOBAL)", "PATIO BONITO II (KENNEDY)", "CHARALA (USME)", "LA PERSEVERANCIA (SANTA FE)", "BOLONIA (USME)", "SAN MIGUEL (BARRIOS UNIDOS)", "LA SOLEDAD NORTE (ENGATIVA)", "SAN MARTIN (SANTA FE)", "LA PEPITA (LOS MARTIRES)", "SAN JOSE SUR (RAFAEL URIBE URIBE)", "LOS LAURELES (BOSA)", "ALQUERIA (PUENTE ARANDA)", "CHAPINERITO (USME)", "OSORIO XII (KENNEDY)", "VISION DE ORIENTE (KENNEDY)", "ORTEZAL (PUENTE ARANDA)", "EL MINUTO DE DIOS (ENGATIVA)", "EL TINTAL CENTRAL (FONTIBON)", "DOCE DE OCTUBRE (BARRIOS UNIDOS)", "LA LIBERTAD (BARRIOS UNIDOS)", "SAN PEDRO (SAN CRISTOBAL)", "GRAN YOMASA (USME)", "POTRERILLO (SUBA)", "SAN MARTIN SUR (SAN CRISTOBAL)", "TUNJUELITO (TUNJUELITO)", "COMPARTIR (CIUDAD BOLIVAR)", "LOS ANGELES (ENGATIVA)", "USAQUEN (USAQUEN)", "TABORA (ENGATIVA)", "SAN BENITO (TUNJUELITO)", "BERLIN (SUBA)", "VILLA MARIA (SUBA)", "NUEVA TIBABUYES (SUBA)", "CANTAGALLO (SUBA)", "LOS CEREZOS (ENGATIVA)", "CERRO COLORADO (CIUDAD BOLIVAR)", "SANTA MATILDE (PUENTE ARANDA)", "ESTRELLA DEL SUR (CIUDAD BOLIVAR)", "SOCIEGO (SAN CRISTOBAL)", "CIUDAD TECHO II (KENNEDY)", "PRADO VERANIEGO NORTE (SUBA)", "BELLAVISTA OCCIDENTAL (ENGATIVA)", "BUENOS AIRES (SAN CRISTOBAL)", "LOMBARDIA (SUBA)", "LAS MERCEDES SUBA (SUBA)", "LAS MANAS (CIUDAD BOLIVAR)", "PALOQUEMAO (LOS MARTIRES)", "SAMPER (SANTA FE)", "JOSE MARIA CARBONEL (BOSA)", "ALTAMIRA (SAN CRISTOBAL)", "SAN JOAQUIN (ENGATIVA)", "GRAN AMERICA (TEUSAQUILLO)", "CENTRO FONTIBON (FONTIBON)", "MOLINOS DEL SUR (RAFAEL URIBE URIBE)", "EL PEDREGAL II (USME)", "TUNA (SUBA)", "VERAGUAS (LOS MARTIRES)", "EL REAL (ENGATIVA)", "CEMENTERIO JARDINES APOGEO (BOSA)", "CERROS DE ORIENTE (RAFAEL URIBE URIBE)", "CANAVERALEJO (BOSA)", "IBERIA (SUBA)", "BRISAS DEL LLANO (USME)", "SEMINARIO (CHAPINERO)", "VICTORIA NORTE (SUBA)", "CHAPINERO CENTRAL (CHAPINERO)", "EL CORZO (BOSA)", "SAN BERNARDINO II (BOSA)", "POPULAR MODELO (BARRIOS UNIDOS)", "SAN PATRICIO (USAQUEN)", "VILLA SAGRARIO (ENGATIVA)", "SAN BLAS (SAN CRISTOBAL)", "SAN JAVIER (SAN CRISTOBAL)", "GRAN COLOMBIANO (BOSA)", "LA PICOTA (RAFAEL URIBE URIBE)", "BAVARIA (KENNEDY)", "MARRUECOS (RAFAEL URIBE URIBE)", "LOS ANDES (BARRIOS UNIDOS)", "COLSEGUROS (LOS MARTIRES)", "REMANSO SUR (PUENTE ARANDA)", "EL NUEVO PORTAL II (USME)", "EL TINTAL IV (KENNEDY)", "VILLA ANITA (USME)", "BELLA FLOR SUR (CIUDAD BOLIVAR)", "BOLIVIA (ENGATIVA)", "ARBORIZADORA ALTA (CIUDAD BOLIVAR)", "BOLONIA I (USME)", "CASABLANCA SUBA (SUBA)", "DINDALITO (KENNEDY)", "EL BAGAZAL (CHAPINERO)", "EL CEDRO (ENGATIVA)", "EL JAZMIN (KENNEDY)", "ESCOCIA (BOSA)", "LA CABANA (USME)", "LOS ALAMOS (ENGATIVA)", "LOS ARRAYANES (USME)", "PASQUILLA (CIUDAD BOLIVAR)", "PERDOMO ALTO (CIUDAD BOLIVAR)", "PROVIVIENDA OCCIDENTAL (KENNEDY)", "SAN BERNARDINO XVIII (BOSA)", "SANTA CECILIA (SUBA)", "SIERRA MORENA (CIUDAD BOLIVAR)", "TIBABUYES (SUBA)"
    };

    private GoogleMap map;

    public SeccionBuscarFragment() {

    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_seccion_buscar, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        zonas_bogota= new ArrayList<Zona>();
        System.out.println("Rev1:\tCargó completo");
        //zonas_bogota=getArguments().getParcelableArrayList("LISTA");

        /*
        for (int i=0; i<zonas_bogota.size(); i++){
            barrios_y_localidades.add(zonas_bogota.get(i).Nombre);
        }
        */

        SupportMapFragment mapFragment = (SupportMapFragment) getChildFragmentManager().findFragmentById(R.id.mapView);
        mapFragment.getMapAsync(this);

        botonVenta= (Button) view.findViewById(R.id.buttonVenta);
        botonArriendo= (Button) view.findViewById(R.id.buttonArriendo);
        botonAceptar= (Button) view.findViewById(R.id.buttonBuscar);
        publicarInmueble= (TextView) view.findViewById(R.id.textViewOlvidasteContrasenaLogin);

        botonAceptar.setEnabled(false);
        botonAceptar.setBackground(getResources().getDrawable(R.drawable.boton_inactivo_redondo));

        botonAceptar.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //Toast.makeText(getActivity(), "Boton aun no programado", Toast.LENGTH_SHORT).show();
                String ofertaPaso="";
                if(botonVenta.getBackground().getConstantState().equals(getResources().getDrawable(R.drawable.boton_activo_redondo).getConstantState())){
                    ofertaPaso="VENTA";
                }
                else{
                    ofertaPaso="ARRIENDO";
                }

                FragmentTransaction fragmentTransaction = getParentFragment().getChildFragmentManager().beginTransaction();
                MiBusquedaFragment miBusquedaFragment= new MiBusquedaFragment(espacio_barrio.getText().toString(), ofertaPaso);
                fragmentTransaction.replace(R.id.contenedor_ppal_buscar, miBusquedaFragment);
                fragmentTransaction.commit();
            }
        });

        botonVenta.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                botonVenta.setBackground(getResources().getDrawable(R.drawable.boton_activo_redondo));
                botonArriendo.setBackground(getResources().getDrawable(R.drawable.boton_inactivo_redondo));
                ofertaTipoVenta=true;
            }
        });

        botonArriendo.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                botonArriendo.setBackground(getResources().getDrawable(R.drawable.boton_activo_redondo));
                botonVenta.setBackground(getResources().getDrawable(R.drawable.boton_inactivo_redondo));
                ofertaTipoVenta=false;
            }
        });

        publicarInmueble.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Navigation.findNavController(view).navigate(R.id.navigation_perfil);
            }
        });



        //--------------------------------↓↓↓Lectura Zonas.txt↓↓↓-----------------------------------
        InputStream is= this.getResources().openRawResource(R.raw.zonas);
        BufferedReader reader= new BufferedReader(new InputStreamReader(is));
        int contador=0;
        String linea;
        if(is!=null){
            try {
                while((linea=reader.readLine())!=null){
                    if(contador==999){
                        StringTokenizer stAtributos= new StringTokenizer(linea,"***");
                        String nombreZona= stAtributos.nextToken();
                        String boundarys= stAtributos.nextToken();
                        boundarys= boundarys.substring(boundarys.indexOf("-")).replace(")","").replace("(","");
                        //System.out.println("LUCHO: boundaries-> "+boundarys);
                        StringTokenizer stCoordenadas= new StringTokenizer(boundarys, ", ");
                        ArrayList<LatLng> puntos_zona_paso= new ArrayList<>();
                        while (stCoordenadas.hasMoreTokens()){
                            String longitud = stCoordenadas.nextToken();
                            String latitud = stCoordenadas.nextToken();
                            //System.out.println("LUCHO: lat-> "+latitud+", Long-> "+longitud);
                            LatLng punto_boundary= new LatLng(Double.parseDouble(latitud), Double.parseDouble(longitud));
                            puntos_zona_paso.add(punto_boundary);
                        }
                        zonas_bogota.add(new Zona(nombreZona, puntos_zona_paso));
                    }
                    else{
                        //Leyendo primera linea. Encabezados
                        contador=999;
                    }
                }
            }
            catch (IOException e){
                System.out.println("LUCHO: problema con la lectura de zonas");
            }
            finally {
                try {
                    if(reader!=null){
                        reader.close();
                    }
                    if (is!=null){
                        is.close();
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

        }
        //--------------------------------↑↑↑Lectura Zonas.txt↑↑↑-----------------------------------


        //-------------------↓↓↓Autocompletar y detectar cambios↓↓↓---------------------------------
        espacio_barrio= (AutoCompleteTextView) view.findViewById(R.id.espacio_barrio);
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(getActivity(),
                R.layout.autocomplete_layout, R.id.visor_autocomplete, barrios_y_localidades);
        espacio_barrio.setAdapter(adapter);
        espacio_barrio.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {

            }

            @Override
            public void afterTextChanged(Editable s) {

                boolean zona_existe=false;
                int indice_zona=-1;
                for (int i=0; i<zonas_bogota.size(); i++){
                    if (zonas_bogota.get(i).Nombre.equals(espacio_barrio.getText().toString())){
                        zona_existe=true;
                        indice_zona=i;
                        break;
                    }
                }
                if (zona_existe){
                    map.clear();
                    InputMethodManager methodManager= (InputMethodManager) espacio_barrio.getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
                    methodManager.hideSoftInputFromWindow(espacio_barrio.getWindowToken(), 0);
                    int margen=10;
                    botonAceptar.setEnabled(true);
                    PolygonOptions polygonOptions= new PolygonOptions();
                    polygonOptions.fillColor(R.color.zona);
                    polygonOptions.addAll(zonas_bogota.get(indice_zona).puntos);
                    polygonOptions.strokeWidth(0);
                    map.addPolygon(polygonOptions);

                    //Polygon pol= map.addPolygon(new PolygonOptions().addAll(zonas_bogota.get(indice_zona).puntos).fillColor(R.color.zona));
                    //pol.setFillColor(R.color.zona);
                    //pol.set
                    //pol.setStrokeWidth(0);
                    //System.out.println("LUCHO: 2 color= "+ pol.getFillColor()+" --- "+R.color.zona);
                    final LatLngBounds espacio_zona= getPolygonLatLngBounds(zonas_bogota.get(indice_zona).puntos);
                    map.moveCamera(CameraUpdateFactory.newLatLngBounds(espacio_zona, margen));
                    botonAceptar.setEnabled(true);
                    botonAceptar.setBackground(getResources().getDrawable(R.drawable.boton_aceptar_redondo));
                }
                else{
                    botonAceptar.setEnabled(false);
                    botonAceptar.setBackground(getResources().getDrawable(R.drawable.boton_inactivo_redondo));
                }
            }
        });
        //----------------------------↑↑↑Autocompletar con zonas↑↑↑---------------------------------
    }

    @Override
    public void onMapReady(GoogleMap googleMap) {
        map= googleMap;
        LatLng bogota= new LatLng(4.60971,-74.08175);
        map.addMarker(new MarkerOptions()
                .position(bogota)
                .title("Bogotá"));
        map.moveCamera(CameraUpdateFactory.newLatLngZoom(bogota,10));
    }

    private static LatLngBounds getPolygonLatLngBounds(final List<LatLng> polygon){
        final LatLngBounds.Builder centeBuilder = LatLngBounds.builder();
        for(LatLng punto : polygon){
            centeBuilder.include(punto);
        }
        return centeBuilder.build();
    }
}